import { Restaurant, MenuItem, GroceryProduct, Flight } from '../types';

// ─── Restaurants ──────────────────────────────────────────────────────────────

export const RESTAURANTS: Restaurant[] = [
  {
    id: 'r001',
    name: 'Burger Singh',
    cuisine: 'Burgers, Fast Food',
    rating: 4.3,
    deliveryTime: '25-35 min',
    deliveryFee: 29,
    minOrder: 149,
    platform: 'swiggy',
    imageEmoji: '🍔',
  },
  {
    id: 'r002',
    name: 'Pizza Hut',
    cuisine: 'Pizza, Italian',
    rating: 4.1,
    deliveryTime: '30-40 min',
    deliveryFee: 0,
    minOrder: 299,
    platform: 'swiggy',
    imageEmoji: '🍕',
  },
  {
    id: 'r003',
    name: 'Behrouz Biryani',
    cuisine: 'Biryani, Mughlai',
    rating: 4.5,
    deliveryTime: '35-45 min',
    deliveryFee: 49,
    minOrder: 299,
    platform: 'zomato',
    imageEmoji: '🍛',
  },
  {
    id: 'r004',
    name: 'KFC',
    cuisine: 'Chicken, Fast Food',
    rating: 4.2,
    deliveryTime: '20-30 min',
    deliveryFee: 0,
    minOrder: 199,
    platform: 'zomato',
    imageEmoji: '🍗',
  },
  {
    id: 'r005',
    name: 'Social',
    cuisine: 'Continental, Bar Food',
    rating: 4.4,
    deliveryTime: '40-50 min',
    deliveryFee: 59,
    minOrder: 399,
    platform: 'swiggy',
    imageEmoji: '🥗',
  },
  {
    id: 'r006',
    name: 'Chai Point',
    cuisine: 'Beverages, Snacks',
    rating: 4.0,
    deliveryTime: '15-25 min',
    deliveryFee: 19,
    minOrder: 99,
    platform: 'zomato',
    imageEmoji: '☕',
  },
  {
    id: 'r007',
    name: 'Paradise Biryani',
    cuisine: 'Biryani, Hyderabadi',
    rating: 4.6,
    deliveryTime: '40-50 min',
    deliveryFee: 39,
    minOrder: 249,
    platform: 'swiggy',
    imageEmoji: '🍚',
  },
  {
    id: 'r008',
    name: 'Dominos',
    cuisine: 'Pizza, Pasta',
    rating: 4.0,
    deliveryTime: '25-35 min',
    deliveryFee: 0,
    minOrder: 199,
    platform: 'zomato',
    imageEmoji: '🍕',
  },
];

// ─── Menu Items ───────────────────────────────────────────────────────────────

export const MENU_ITEMS: Record<string, MenuItem[]> = {
  r001: [
    { id: 'm001', name: 'Classic Burger', description: 'Juicy beef patty with lettuce, tomato, cheese', price: 199, category: 'Burgers', isVeg: false, isPopular: true },
    { id: 'm002', name: 'Veggie Delight', description: 'Crispy veggie patty with special sauce', price: 149, category: 'Burgers', isVeg: true, isPopular: false },
    { id: 'm003', name: 'Loaded Fries', description: 'Fries with cheese sauce and jalapeños', price: 129, category: 'Sides', isVeg: true, isPopular: true },
  ],
  r002: [
    { id: 'm010', name: 'Margherita Pizza', description: 'Classic tomato sauce with mozzarella', price: 349, category: 'Pizzas', isVeg: true, isPopular: true },
    { id: 'm011', name: 'Pepperoni Pizza', description: 'Loaded with pepperoni and cheese', price: 449, category: 'Pizzas', isVeg: false, isPopular: true },
    { id: 'm012', name: 'Garlic Bread', description: 'Toasted bread with garlic butter', price: 129, category: 'Sides', isVeg: true, isPopular: false },
  ],
  r003: [
    { id: 'm020', name: 'Chicken Biryani', description: 'Fragrant basmati rice with tender chicken', price: 399, category: 'Biryani', isVeg: false, isPopular: true },
    { id: 'm021', name: 'Veg Biryani', description: 'Aromatic biryani with fresh vegetables', price: 299, category: 'Biryani', isVeg: true, isPopular: false },
    { id: 'm022', name: 'Mutton Biryani', description: 'Slow-cooked mutton in spiced rice', price: 499, category: 'Biryani', isVeg: false, isPopular: true },
  ],
};

// ─── Grocery Products ─────────────────────────────────────────────────────────

export const GROCERY_PRODUCTS: GroceryProduct[] = [
  { id: 'g001', name: 'Amul Full Cream Milk', brand: 'Amul', unit: '500ml', price: 29, originalPrice: 32, platform: 'blinkit', deliveryTime: '10 min', imageEmoji: '🥛' },
  { id: 'g002', name: 'Britannia Good Day Cookies', brand: 'Britannia', unit: '250g', price: 55, originalPrice: 60, platform: 'blinkit', deliveryTime: '10 min', imageEmoji: '🍪' },
  { id: 'g003', name: 'Tata Salt', brand: 'Tata', unit: '1kg', price: 23, originalPrice: 25, platform: 'zepto', deliveryTime: '8 min', imageEmoji: '🧂' },
  { id: 'g004', name: 'Lay\'s Classic Salted Chips', brand: 'Lay\'s', unit: '78g', price: 20, originalPrice: 20, platform: 'blinkit', deliveryTime: '10 min', imageEmoji: '🥔' },
  { id: 'g005', name: 'Coca Cola', brand: 'Coca Cola', unit: '750ml', price: 45, originalPrice: 50, platform: 'zepto', deliveryTime: '8 min', imageEmoji: '🥤' },
  { id: 'g006', name: 'Fortune Sunflower Oil', brand: 'Fortune', unit: '1L', price: 145, originalPrice: 165, platform: 'blinkit', deliveryTime: '10 min', imageEmoji: '🫙' },
  { id: 'g007', name: 'Aashirvaad Atta', brand: 'Aashirvaad', unit: '5kg', price: 289, originalPrice: 310, platform: 'zepto', deliveryTime: '8 min', imageEmoji: '🌾' },
  { id: 'g008', name: 'Mother Dairy Curd', brand: 'Mother Dairy', unit: '500g', price: 45, originalPrice: 48, platform: 'blinkit', deliveryTime: '10 min', imageEmoji: '🥣' },
  { id: 'g009', name: 'Red Bull Energy Drink', brand: 'Red Bull', unit: '250ml', price: 125, originalPrice: 130, platform: 'zepto', deliveryTime: '8 min', imageEmoji: '🧃' },
  { id: 'g010', name: 'Haldiram\'s Aloo Bhujia', brand: 'Haldiram\'s', unit: '400g', price: 145, originalPrice: 155, platform: 'blinkit', deliveryTime: '10 min', imageEmoji: '🥨' },
];

// ─── Flights ──────────────────────────────────────────────────────────────────

export const FLIGHTS: Flight[] = [
  {
    id: 'f001',
    airline: 'IndiGo',
    flightNo: '6E-204',
    origin: 'DEL',
    destination: 'BOM',
    departure: '06:15',
    arrival: '08:30',
    duration: '2h 15m',
    price: 4299,
    class: 'economy',
    seatsLeft: 12,
    imageEmoji: '✈️',
  },
  {
    id: 'f002',
    airline: 'Air India',
    flightNo: 'AI-101',
    origin: 'DEL',
    destination: 'BOM',
    departure: '09:00',
    arrival: '11:25',
    duration: '2h 25m',
    price: 5899,
    class: 'economy',
    seatsLeft: 28,
    imageEmoji: '✈️',
  },
  {
    id: 'f003',
    airline: 'Vistara',
    flightNo: 'UK-995',
    origin: 'DEL',
    destination: 'BOM',
    departure: '12:40',
    arrival: '15:00',
    duration: '2h 20m',
    price: 7299,
    class: 'business',
    seatsLeft: 4,
    imageEmoji: '✈️',
  },
  {
    id: 'f004',
    airline: 'SpiceJet',
    flightNo: 'SG-116',
    origin: 'DEL',
    destination: 'BLR',
    departure: '07:30',
    arrival: '10:05',
    duration: '2h 35m',
    price: 3899,
    class: 'economy',
    seatsLeft: 35,
    imageEmoji: '✈️',
  },
  {
    id: 'f005',
    airline: 'IndiGo',
    flightNo: '6E-308',
    origin: 'BOM',
    destination: 'DEL',
    departure: '14:00',
    arrival: '16:20',
    duration: '2h 20m',
    price: 4599,
    class: 'economy',
    seatsLeft: 8,
    imageEmoji: '✈️',
  },
  {
    id: 'f006',
    airline: 'Air India',
    flightNo: 'AI-665',
    origin: 'DEL',
    destination: 'CCU',
    departure: '11:15',
    arrival: '13:30',
    duration: '2h 15m',
    price: 3699,
    class: 'economy',
    seatsLeft: 20,
    imageEmoji: '✈️',
  },
];

// ─── City Code Map ─────────────────────────────────────────────────────────────

export const CITY_CODES: Record<string, string> = {
  'delhi': 'DEL', 'new delhi': 'DEL', 'del': 'DEL',
  'mumbai': 'BOM', 'bombay': 'BOM', 'bom': 'BOM',
  'bangalore': 'BLR', 'bengaluru': 'BLR', 'blr': 'BLR',
  'kolkata': 'CCU', 'calcutta': 'CCU', 'ccu': 'CCU',
  'chennai': 'MAA', 'madras': 'MAA', 'maa': 'MAA',
  'hyderabad': 'HYD', 'hyd': 'HYD',
  'pune': 'PNQ', 'pnq': 'PNQ',
  'ahmedabad': 'AMD', 'amd': 'AMD',
  'goa': 'GOI', 'goi': 'GOI',
};
